version: "3.9"
services:

  # http://127.0.0.1:3000
  vroom:
    image: vroomvrp/vroom-docker:v1.13.0
    hostname: vroom
    container_name: vroom
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./vroom-conf:/conf:rw
    environment:
      VROOM_ROUTER: ors
    depends_on:
      ors:
        condition: service_started
    healthcheck:
      test: curl --fail --silent http://localhost:3000/health --output /dev/null || exit 1
      interval: 1s
      timeout: 2s
      retries: 10

  ors:
    image: openrouteservice/openrouteservice:v7.1.1
    container_name: ors
    hostname: ors
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9001:9001"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - ./graphs:/home/ors/ors-core/data/graphs
      - ./elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./logs/ors:/home/ors/ors-core/logs/ors
      - ./logs/tomcat:/home/ors/tomcat/logs
      - ./ors-conf:/home/ors/ors-conf
      - ./pbf/austria-latest.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
    healthcheck:
      test: nc -z -v ors 8080
      interval: 1s
      timeout: 2s
      retries: 600